# Generated by Django 5.0 on 2023-12-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysentform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_images/'),
        ),
    ]
